# Generated by Django 4.1.2 on 2022-11-29 23:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ip', models.CharField(max_length=15, validators=[django.core.validators.validate_ipv4_address])),
                ('dest_ip', models.CharField(max_length=15, validators=[django.core.validators.validate_ipv4_address])),
                ('source_port', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(65635), django.core.validators.MinValueValidator(1)])),
                ('dest_port', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(65635), django.core.validators.MinValueValidator(1)])),
                ('PROTOCOL_TYPES', models.CharField(choices=[('ICMPv4:8', 'ICMPv4 - ECHO'), ('ipv6', 'IPv6'), ('UDP', 'UDP'), ('TCP', 'TCP')], max_length=10)),
                ('ACTION', models.CharField(choices=[('Allow', 'Allow'), ('Block', 'Block')], max_length=10)),
                ('DIR', models.CharField(choices=[('in', 'Inbound'), ('out', 'Outbound')], max_length=15)),
            ],
            options={
                'db_table': 'Rules',
            },
        ),
    ]
